kind: pipeline
type: exec
name: x86_64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - /bin/sh ./build.sh

- name: upload
  commands:
  - apk add minio-client
  - /bin/sh ./upload.sh
  environment:
    MC_HOST_master:
      from_secret: MC_HOST_master
  when:
    branch:
    - master

---
kind: pipeline
type: exec
name: aarch64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  commands:
  - /bin/sh ./build.sh

- name: upload
  commands:
  - apk add minio-client
  - /bin/sh ./upload.sh
  environment:
    MC_HOST_master:
      from_secret: MC_HOST_master
  when:
    branch:
    - master

---
kind: pipeline
type: exec
name: ppc64le

platform:
  os: linux
  arch: ppc64le

steps:
- name: build
  commands:
  - /bin/sh ./build.sh

- name: upload
  commands:
  - apk add minio-client
  - /bin/sh ./upload.sh
  environment:
    MC_HOST_master:
      from_secret: MC_HOST_master
  when:
    branch:
    - master
